# Generated by Django 3.2.9 on 2021-12-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='order_line_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Giftcards', to='checkout.orderlineitem'),
            preserve_default=False,
        ),
    ]
