# Generated by Django 3.2.9 on 2022-01-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220118_1856'),
        ('checkout', '0006_giftcard_order_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productinventory'),
        ),
    ]
