# Generated by Django 3.2.9 on 2021-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211111_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sale_percent',
            field=models.IntegerField(default=0),
        ),
    ]
