# Generated by Django 3.2.9 on 2021-12-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_sale_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='giftcard_category',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
