# Generated by Django 3.2.9 on 2022-01-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='image_url',
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colour')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcolour'),
        ),
    ]
