# Generated by Django 3.2.9 on 2022-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220118_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={},
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.UniqueConstraint(fields=('journal_id', 'volume_number'), name='name of constraint'),
        ),
    ]
