# Generated by Django 3.2.9 on 2022-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220118_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name_plural': 'Product Inventory'},
        ),
        migrations.RemoveConstraint(
            model_name='productinventory',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='productcolour',
            constraint=models.UniqueConstraint(fields=('product', 'colour'), name='product_colour_constraint'),
        ),
    ]
